# 加载顺序是 yaml > yml > properties, 优先级则相反。
dubbo:
    application:
        id: dubbo-service
        name: dubbo-service
    enabled: true
    protocol:
        name: dubbo
        port: 20880
    registry:
        address: zookeeper://127.0.0.1:2181
    scan:
        base-packages: com.example.demo.service
logging:
    level:
        root: info
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.hundun.demo.entity

spring:
    application:
        name: demo-service
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/demo?serverTimezone=UTC
        username: root
    messages:
        basename: static/i18n/common_message
