spring:
  application:
    name: demo-service
  messages:
    basename: static/i18n/common_message

person:
  age: 12
  name: "123"

logging:
  level:
    root: info

dubbo:
  # 是否启用 springboot-dubbo
  enabled: true
  application:
    name: dubbo-service
    id: dubbo-service
  scan:
    # 包名根据自己的实际情况写
    base-packages: com.example.demo.service
  protocol:
    port: 20880
    name: dubbo
  registry:
    #zookeeper注册中心地址
    address: zookeeper://127.0.0.1:2181